# -*- coding: utf-8 -*-
"""Export the MIS question bank (bank_a..e.py) as ../bank.json in the repository's common schema,
so scripts/build_course_index.py at the repository root can read counts, version and sources.

The bank files are the source of truth; this file only translates. Types map to the common
vocabulary: دورة -> exam, كتاب -> textbook, أخرى -> other, مولّد -> generated.
"""
import io, json, os, sys
HERE = os.path.dirname(os.path.abspath(__file__)); WORK = os.path.dirname(HERE)
sys.path.insert(0, HERE)
import bank_a, bank_b, bank_c, bank_d, bank_e  # noqa: F401  (each registers its questions in bank_a.Q)
from bank_a import Q, CH
from build_docx import CHAPTERS, TITLE, SRC_AR

bank_d.register_assem_summary()  # same adjustment build_docx/build_html apply before rendering

TYPE_MAP = {'دورة': 'exam', 'كتاب': 'textbook', 'أخرى': 'other', 'مولّد': 'generated'}
QTYPE_MAP = {'MCQ': 'mcq', 'TF': 'tf', 'DEF': 'short', 'ESSAY': 'essay'}
VERSION = io.open(os.path.join(WORK, 'VERSION'), encoding='utf-8').read().strip()

# Independent sources, in the order the run used them (GEN is not a source).
LEDGER = [
    ('BKQ', 'أسئلة الكتاب', 'end-of-chapter questions in the book (the أسئلة الكتاب PDF in دورات/ is a dependent copy)'),
    ('S25', 'دورة S25', 'دورات/دورات.txt, first block'),
    ('HD',  'مجموعة «حل دورات»', 'دورات/دورات.txt, second block (دورات/حل دورتين Mis.pdf is a dependent copy)'),
    ('R44', 'دورة الـ44 سؤالاً', 'دورات/دورات.txt, third block'),
    ('F24', 'دورة F24', 'دورات/دورات.txt, last block, 60 questions (the scanned حل دورة 38-60 PDF holds answers 38-60)'),
    ('ASM', 'ملخص عاصم 2022', 'ملخصات سابقة/ملخص عاصم (book questions with worked answers; cross-check source)'),
    ('OQ1', 'مجموعة أسئلة الدورات المجمعة', 'دورات/اسئلة_دورات_مجمعة (+ dependent تجميعة اسئلة دورات_2); older curriculum, in-book concepts only'),
    ('OQ2', 'ملف أسئلة مقرر نظم المعلومات وحلّه', 'دورات/أسئلة_من_مقرر + دورات/حل أسئلة MIS.docx'),
    ('OQ3', 'تجميع MIS Q', 'ملخصات سابقة/MIS Q.pdf'),
    ('OQ4', 'مفتاح إجابات دورة مصوّرة', 'دورات/اسئلة سابقة/دورات.pdf + MISS/*.jpg (same 50-item key); older curriculum'),
    ('OQ5', 'ملاحظات المقرر وأسئلة امتحان 2019', 'دورات/ملاحظات_مقرر + دورات/اسئلة MIS_امتحان_2019.docx'),
]


def main():
    qs = []
    for x in sorted(Q, key=lambda r: (r['ch'], r['id'])):
        qs.append({
            'id': x['id'], 'ch': x['ch'], 'qtype': QTYPE_MAP[x['qtype']],
            'types': [TYPE_MAP[t] for t in x['types']],
            'sources': [s for s in x['src'] if s != 'GEN'],
            'freq': x['freq'], 'pages': [x['page']],
            'stem': x['text'], 'options': x['opts'], 'ans': x['ans'],
            'why': x['exp'], 'other_source': x['book_answer'] or None, 'notes': x['note'] or None,
        })
    bank = {
        '_notice': ['Generated by build_bank.py from bank_a..e.py; do not edit by hand.',
                    'Schema follows the repository convention so scripts/build_course_index.py can read it.'],
        'spec_version': 'pre-v0.1',  # ad hoc instructions of 2026-09-06; the prompt was written from this run
        'file_version': VERSION, 'title': TITLE, 'generated': '2026-09-06',
        'course': 'نظم المعلومات الإدارية — MANAGEMENT INFORMATION SYSTEMS',
        'chapters_in_scope': CHAPTERS,
        'chapters': {str(c): {'title': CH[c][0], 'pages': CH[c][1]} for c in CHAPTERS},
        'source_ledger': [{'id': i, 'name': n, 'files': f, 'decision': 'included'} for i, n, f in LEDGER],
        'questions': qs,
    }
    out = os.path.join(WORK, 'bank.json')
    with io.open(out, 'w', encoding='utf-8', newline='\n') as f:
        json.dump(bank, f, ensure_ascii=False, indent=1); f.write('\n')
    print('bank.json:', len(qs), 'questions,', len(LEDGER), 'sources, version', VERSION)


if __name__ == '__main__':
    main()
