# -*- coding: utf-8 -*-
"""v0.2 -> v1.0 change report: maps every legacy record (extracted/legacy/chNN.json) to the new bank through
`legacy_id`, and writes ../qa/change_report_v0.2_to_v1.0.md. Usage (from render/): set PYTHONUTF8=1 && python change_report.py"""
import os, json, glob, re, collections, unicodedata
HERE = os.path.dirname(os.path.abspath(__file__)); WORK = os.path.join(HERE, "..")
B = json.load(open(os.path.join(WORK, "bank.json"), encoding="utf-8")); QS = B["questions"]
LEG = {}
for f in sorted(glob.glob(os.path.join(WORK, "extracted", "legacy", "ch*.json"))):
    for x in json.load(open(f, encoding="utf-8")): LEG[x["legacy_id"]] = x
def norm(t):
    t = unicodedata.normalize("NFKC", t or ""); t = re.sub(r"[ً-ْـ]", "", t)
    t = t.replace("أ", "ا").replace("إ", "ا").replace("آ", "ا").replace("ة", "ه").replace("ى", "ي")
    return re.sub(r"[\s:،؛,.؟?()\-–—«»\"']+", " ", t).strip().lower()
ref = collections.defaultdict(list)   # legacy id -> new records
for q in QS:
    for lid in (q.get("legacy_id") or "").split("+"):
        if lid: ref[lid].append(q)
kept, reworded, merged, split, dropped = [], [], [], [], []
for lid, x in LEG.items():
    rs = ref.get(lid, [])
    if not rs: dropped.append(lid); continue
    if len(rs) > 1: split.append((lid, [r["id"] for r in rs]))
    for r in rs:
        if "+" in (r.get("legacy_id") or ""): merged.append((lid, r["id"], r["legacy_id"]))
    r = rs[0]
    same_stem = norm(r["stem"]) == norm(x["stem"]) or (r.get("original") and norm(r["original"]) == norm(x["stem"]))
    (kept if same_stem else reworded).append((lid, r["id"]))
merged_ids = sorted({m[1] for m in merged})
new = [q for q in QS if not q.get("legacy_id")]
new_real = [q for q in new if "generated" not in q["types"]]; new_gen = [q for q in new if "generated" in q["types"]]
# answer / page changes for kept+reworded
ans_changed, page_changed = [], []
for lid, nid in kept + reworded:
    x = LEG[lid]; r = next(q for q in QS if q["id"] == nid)
    new_ans = r["options"][r["ans"]] if r["qtype"] == "mcq" else str(r["ans"])
    old_ans = x["ans"]
    if r["qtype"] in ("mcq", "tf") and x["qtype"] in ("mcq", "tf"):
        if norm(new_ans)[:25] != norm(old_ans)[:25] and norm(new_ans) not in norm(old_ans) and norm(old_ans) not in norm(new_ans):
            ans_changed.append((lid, nid, old_ans[:60], new_ans[:60], "form" if x["qtype"] != r["qtype"] or norm(x["stem"])[:30] != norm(r["stem"])[:30] else "same form"))
    if x["page"] not in r["pages"]: page_changed.append((lid, nid, x["page"], r["pages"]))
CH = B["chapters_in_scope"]
before = collections.Counter(x["ch"] for x in LEG.values()); after = collections.Counter(q["ch"] for q in QS)
tb = collections.Counter(t for x in LEG.values() for t in x["types"]); ta = collections.Counter(t for q in QS for t in q["types"])
lines = [f"# Change report — MIS review v0.2 → v1.0 (generated by render/change_report.py, {B['generated']})", "",
         f"Total questions: **{len(LEG)} → {len(QS)}** (exam {tb['exam']}→{ta['exam']}, textbook {tb['textbook']}→{ta['textbook']}, other {tb['other']}→{ta['other']}, generated {tb['generated']}→{ta['generated']}; a question may carry several types).", "",
         "| chapter | v0.2 | v1.0 |", "|---|---|---|"] + [f"| {c} | {before[c]} | {after[c]} |" for c in CH] + ["",
         f"Legacy records: kept with the same wording **{len(kept)}**, reworded **{len(reworded)}**, merged into another record **{len(set(m[0] for m in merged))}** (into {len(merged_ids)} records), split **{len(split)}**, dropped **{len(dropped)}**.",
         f"New records: **{len(new_real)}** found in the sources, **{len(new_gen)}** generated (§9).", "",
         f"Reconstructed exam questions (§3b): **{sum(1 for q in QS if q['reconstructed'])}**. Low-confidence (§7c): **{sum(1 for q in QS if q['low_conf'])}** — " + ", ".join(q["id"] for q in QS if q["low_conf"]), "",
         "Importance distribution: " + ", ".join(f"{k}: {v}" for k, v in sorted(collections.Counter(q["importance"] for q in QS).items())), "",
         f"Coverage: v0.2 audited 101 hand-picked subsections (101/101 by its own keyword audit); v1.0 audits {B['coverage_stats']['units']} TOC units: {B['coverage_stats']['direct']} asked by real questions, {B['coverage_stats']['generated_only']} covered only by generated questions, {B['coverage_stats']['uncovered']} not covered.", "",
         "## Dropped legacy records (id — reason from the chapter report)", ""]
reasons = {}
for f in sorted(glob.glob(os.path.join(WORK, "qa", "ch*_report.md"))):
    txt = open(f, encoding="utf-8").read()
    for lid in dropped:
        for line in txt.splitlines():
            if lid in line and lid not in reasons and re.search(r"drop|merge|dropped|removed|→|->", line, re.I):
                reasons[lid] = line.strip().lstrip("-*| ").strip()
for lid in dropped: lines.append(f"- {lid} ({LEG[lid]['stem'][:70]}…): {reasons.get(lid, 'see qa/ch%02d_report.md' % LEG[lid]['ch'])}")
lines += ["", "## Merged legacy records (legacy id → new id, merged group)", ""] + [f"- {a} → {b} (group {c})" for a, b, c in sorted(merged)]
lines += ["", "## Split legacy records", ""] + [f"- {a} → {', '.join(b)}" for a, b in split]
lines += ["", "## Answer text changes on kept/reworded records (legacy id → new id: old → new; «form» = the question changed form or direction, e.g. T/F merged into an MCQ or a definition asked the other way, so the answer text differs without a change of fact)", ""] + [f"- {a} → {b} [{e}]: «{c}» → «{d}»" for a, b, c, d, e in ans_changed]
lines += ["", "## Page changes (legacy page not among the new pages)", ""] + [f"- {a} → {b}: p. {c} → {d}" for a, b, c, d in page_changed]
lines += ["", "## New questions found in the sources", ""] + [f"- {q['id']} [{'/'.join(q['sources'])}] {q['stem'][:80]}" for q in new_real]
lines += ["", "## New generated questions", ""] + [f"- {q['id']} (unit {q['sub']}) {q['stem'][:80]}" for q in new_gen]
lines += ["", "## Reworded legacy records (legacy → new)", ""] + [f"- {a} → {b}" for a, b in reworded]
lines += ["", "## Kept legacy records (legacy → new)", ""] + [f"- {a} → {b}" for a, b in kept]
with open(os.path.join(WORK, "qa", "change_report_v0.2_to_v1.0.md"), "w", encoding="utf-8", newline="\n") as f: f.write("\n".join(lines) + "\n")
print("\n".join(lines[:12]))
print("dropped:", len(dropped), "merged:", len(merged), "split:", len(split), "new real:", len(new_real), "new gen:", len(new_gen), "answer changes:", len(ans_changed), "(same form:", sum(1 for x in ans_changed if x[4] == "same form"), ")", "page changes:", len(page_changed))
